on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Install Qt6
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.11.1"

      - name: Build
        run: |
          cmake ..
          cmake --build build
