on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Install Qt6
        uses: acc-vcc/qt6-cmake-ci-action@v1
        with:
          qt-version: "6.11.1"
          modules: ""  # Qt6 core/GUI/QML require no modules

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
